name: circle
description: A new social App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  provider: ^4.3.2+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio_cookie_manager: 1.0.0
  fluttertoast: ^3.0.4
  shared_preferences: ^0.5.7+3
  device_info: ^0.4.2+4
  photo_view: ^0.10.2
  photo: ^0.4.8
  flutter_easyrefresh: ^2.1.1
  extended_nested_scroll_view: ^1.0.1
  flutter_spinkit: "^4.1.2"
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.7
  # Flutter 屏幕适配 https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^2.3.1
  # 展示svg图片 https://github.com/dnfield/flutter_svg
  flutter_svg: 0.17.2
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.2.0+1
  # Flutter 常用工具库 https://github.com/Sky24n/flustars
  flustars: 0.2.6+1
  flutter_sound: ^1.5.2
  video_player: ^0.10.12+2
  image_picker: ^0.6.7+7
  emoji_picker: ^0.1.0
  keyboard_visibility: ^0.5.2 #软键盘
  camera: ^0.5.8+8
  group_list_view: ^1.0.6
  grouped_buttons: ^1.0.4
  # 图片编辑 https://pub.dev/packages/image_cropper/install
  image_cropper: ^1.3.1
  flutter_ffmpeg: ^0.3.0
  permission_handler: ^5.0.1+1
  flutter_plugin_record:
    git:
      url: https://github.com/EnterYang/flutter_plugin_record.git

  flukit:
    git:
      url: git://github.com/flutterchina/flukit.git
      path: package_src/

  im_flutter_sdk:
    git:
      url: https://github.com/easemob/im_flutter_sdk.git
      ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
          style: italic

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
